[package]
name = "synthriders_rs"
version = "0.1.0"
authors = ["Raphaël Thériault <raphael_theriault@outlook.com>"]
edition = "2018"
license = "MIT"

[dependencies]
[dependencies.serde]
version = "1.0.102"
features = ["derive"]
optional = true

[features]
default = ["serde"]
